version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=sa-east-1
      # E se precisar:
      - AWS_DEFAULT_REGION=sa-east-1
    volumes:
      - "./init-scripts:/etc/localstack/init/ready.d/script.sh"
